# Project information
site_name: FolderSync Documentation
site_url: https://foldersync.io/docs/

# Copyright
copyright: Copyright &copy; 2022 Tacit Dynamics Aps

# Configuration
theme:
  name: material
  palette: 
      - media: "(prefers-color-scheme: light)" 
        scheme: default
        toggle:
          icon: material/toggle-switch-off-outline 
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)" 
        scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode  

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.sections
  - toc.follow

  favicon: favicon.png
  icon:
    logo: logo

extra:
  generator: false

markdown_extensions:
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- admonition
- pymdownx.details
- pymdownx.superfences
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Home:
    - Getting started: index.md
  - Userguide:
    - Getting started: 
      - Installation: help/index.md 
      - Permissions: help/permissions.md
      - Settings: help/settings.md
      - Debug logging: help/logging.md
    - Accounts:
      - What is an account: help/accounts.md
      - Add cloud service account: help/cloudservices.md
      - Add file protocol account: help/fileprotocols.md
    - FolderPairs:
      - Creating folderPair: help/folderpairs.md
      - Scheduling: help/scheduling.md
      - Scheduling: help/scheduling.md
      - Notifications: help/notifications.md
      - Filters: help/filters.md
      - Webhooks: help/webhooks.md
      - Automation: help/automation.md
      - Running sync: help/syncing.md
      - Sync status: help/syncstatus.md
  - MDM:
    - Configuration deployment: mdm/index.md
    - Glossary: mdm/glossary.md
    - Creating configuration: mdm/export.md
    - Deploy configuration: mdm/deploy.md
    - Import configuration: mdm/import.md    
  - FAQ:
    - General:
      - Misc: faq/index.md
      - Google Play: faq/googleplay.md 
      - Sync issues: faq/sync.md   
      - Scheduling issues: faq/scheduling.md
    - Accounts:
      - Amazon S3: faq/s3.md     
      - FTP: faq/ftp.md   
      - Google Drive: faq/drive.md
      - PCloud: faq/pcloud.md
      - SFTP: faq/sftp.md   
      - SMB: faq/smb.md   
      - WebDAV: faq/webdav.md   
    